# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact_email',
            new_name='contact_Email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_Code',
            field=models.CharField(default=100, max_length=5),
            preserve_default=False,
        ),
    ]
