# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170529_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default="plop", editable=False, populate_from='username', unique_with=('username',)),
            preserve_default=False,
        ),
    ]
