# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170601_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique_with=('username',)),
        ),
    ]
