# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20170601_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
