# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('people', '0009_profile_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taginterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='taginterest',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Profile'),
        ),
        migrations.AddField(
            model_name='taginterest',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_taginterest_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='people.Taginterest', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
