# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20170615_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BioTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('bio', models.CharField(max_length=1000, verbose_name='Bio')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='people.Bio')),
            ],
            options={
                'managed': True,
                'db_table': 'people_bio_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'bio Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='profiletranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='ProfileTranslation',
        ),
        migrations.AddField(
            model_name='profile',
            name='translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Bio', verbose_name='utilisateur'),
        ),
        migrations.AlterUniqueTogether(
            name='biotranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
