# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20170615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Bio', verbose_name='translation'),
        ),
    ]
