# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20170615_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('bio', models.CharField(max_length=1000, verbose_name='Bio')),
            ],
            options={
                'managed': True,
                'db_table': 'people_profile_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'profile Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='biotranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='biotranslation',
            name='master',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='translation',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.DeleteModel(
            name='BioTranslation',
        ),
        migrations.AddField(
            model_name='profiletranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='people.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
